
DESKTOP_ENVIRONMENT = {
    "<————Official————>": 1,
    "Budgie": "budgie",
    "Cinnamon": "cinnamon",
    "Cutefish": "cutefish",
    "Deepin": "deepin",
    "Enlightenment": "enlightenment",
    "GNOME": "gnome",
    "GNOME Flashback": "gnome-flashback",
    "KDE Plasma": "plasma",
    "LXDE": "lxde-gtk3",
    "LXQt": "lxqt",
    "MATE": "mate",
    "Sugar": "sugar",
    "UKUI": "ukui",
    "Xfce": "xfce4",
    "<————Unofficial————>": 1,
    "CDE": "cdedesktopenv",
    "COSMIC": "cosmic-epoch-git",
    "EDE": "ede",
    "KDE1": "kde1-kdebase-git",
    "Liri": "liri-shell-git",
    "Lumina": "lumina-desktop",
    "Maui Shell": "maui-shell-git",
    "Moksha": "moksha-git",
    "Pantheon": "pantheon-session-git",
    "PaperDE": "paperde",
    "Phosh": "phosh",
    "theDesk": "thedesk"
}

DISPLAY_MANAGER = {
    "<————Console————>": 1,
    "CDM": "cdm",
    "Console TDM": "console-tdm",
    "nodm": "nodm",
    "Ly": "ly",
    "tbsm": "tbsm",
    "emptty": "emptty-git",
    "loginx": "loginx",
    "Lemurs": "lemurs-git",
    "<————Graphical————>": 1,
    "Entrance/Enlightment": "entrance-git",
    "GDM/GNOME": "gdm",
    "LightDM": "lightdm",
    "LXDM/LXDE": "lxdm-gtk3",
    "SDDM": "sddm",
    "SLiM": "slim",
    "XDM": "xorg-xdm",
    "<————Login Daemons————>": 1,
    "greetd": "greetd"
}

KERNEL = {
    "<————Official————>": 1,
    "Stable": "linux",
    "Hardened": "linux-hardened",
    "Longterm": "linux-lts",
    "Realtime Kernel": "linux-rt",
    "Realtime Kernel Lts": "linux-rt-lts",
    "Zen Kernel": "linux-zen",
    "<————Unofficial————>": 1,
    "Ck": "linix-ck",
    "Clear": "linunx-clear",
    "GalliumOS": "linux-galliumos",
    "Libre": "linux-libre",
    "Liquorix": "linux-lqx",
    "pf-Kernel": "linux-pf-git",
    "pf-Kernel Lts": "linux-pf-stable-git",
    "Project C": "linux-prjc",
    "Nitrous": "linux-nitrous",
    "VFIO": "linux-vfio",
    "VFIO Lts": "linux-vfio-lts",
    "XanMod": "linux-xanmod",
    "XanMod Lts": "linux-xanmod-lts",
    "XanMod Rt": "linux-xanmod-rt"
}

LANGUAGE = {"Afrikaans": "af_ZA.UTF-8",
        "Albanian": "sq_AL.UTF-8", 
        "Amharic": "am_ET.UTF-8", 
         
        "Arabic (Algeria)": "ar_DZ.UTF-8", 
        "Arabic (Bahrain)": "ar_BH.UTF-8", 
        "Arabic (Egypt)": "ar_EG.UTF-8",
        "Arabic (Iraq)": "ar_IQ.UTF-8", 
        "Arabic (Jordan)": "ar_JO.UTF-8", 
        "Arabic (Kuwait)": "ar_KW.UTF-8",
        "Arabic (Lebanon)": "ar_LB.UTF-8", 
        "Arabic (Libya)": "ar_LY.UTF-8", 
        "Arabic (Mauritania)": "ar_MR.UTF-8",
        "Arabic (Morocco)": "ar_MA.UTF-8", 
        "Arabic (Oman)": "ar_OM.UTF-8", 
        "Arabic (Qatar)": "ar_QA.UTF-8",
        "Arabic (Saudi Arabia)": "ar_SA.UTF-8", 
        "Arabic (Syria)": "ar_SY.UTF-8", 
        "Arabic (Tunisia)": "ar_TN.UTF-8",
        "Arabic (UAE)": "ar_AE.UTF-8", 
        "Arabic (Yemen)": "ar_YE.UTF-8", 
        
        "Armenia": "hy_AM.UTF-8",
        "Assamese": "as_IN.UTF-8", 
        "Azerbaijani [Latin]": "az_Latn_AZ.UTF-8", 
        "Basque": "eu_ES.UTF-8",
        "Belarusian": "be_BY.UTF-8",
        "Bengali (Bangladesh)": "bn_BD.UTF-8",
        "Bengali (India)": "bn_IN.UTF-8",
        "Bosnian": "bs_Latn_BA.UTF-8", 
        "Bulgarian": "bg_BG.UTF-8",
        "Burmese": "my_MM.UTF-8",
        "Catalan": "ca_ES.UTF-8", 
        
        "Chinese [Hans]": "zh_Hans_CN.UTF-8", 
        "Chinese [Hans] (Singapore)": "zh_Hans_SG.UTF-8",
        "Chinese [Hant] (Hong Kong)": "zh_Hant_HK.UTF-8", 
        "Chinese [Hant] (Macao)": "zh_Hant_MO.UTF-8", 
        "Chinese [Hant] (Taiwan)": "zh_Hant_TW.UTF-8",
        
        "Croatian": "hr_HR.UTF-8", 
        "Czech": "cs_CZ.UTF-8", 
        "Danish": "da_DK.UTF-8",
        
        "Dutch (Belgium)": "nl_BE.UTF-8",
        "Dutch (Netherlands)": "nl_NL.UTF-8", 
        
        "English (Australia)": "en_AU.UTF-8", 
        "English (Beglium)": "en_BE.UTF-8",
        "English (Canada)": "en_CA.UTF-8", 
        "English (Cameroon)": "en_CM.UTF-8", 
        "English (Ghana)": "en_GH.UTF-8",
        "English (Hong Kong)": "en_HK.UTF-8", 
        "English (India)": "en_IN.UTF-8", 
        "English (Ireland)": "en_IE.UTF-8",
        "English (Kenya)": "en_KE.UTF-8", 
        "English (Mauritius)": "en_MU.UTF-8", 
        "English (New Zealand)": "en_NZ.UTF-8",
        "English (Nigeria)": "en_NG.UTF-8", 
        "English (Philipinnes)": "en_PH.UTF-8", 
        "English (Singapore)": "en_SG.UTF-8",
        "English (South Africa)": "en_ZA.UTF-8", 
        "English (Tanzania)": "en_TZ.UTF-8", 
        "English (United Kingdom)": "en_GB.UTF-8",
        "English (United Stated)": "en_US.UTF-8", 
        "English (Zambia)": "en_ZM.UTF-8", 
        
        "Estonian": "et_EE.UTF-8",
        "Filipino [Latin]": "fil_PH.UTF-8", 
        "Finnish": "fi_FI.UTF-8", 
        
        "French (Algeria)": "fr_DZ.UTF-8",
        "French (Beglium)": "fr_BE.UTF-8", 
        "French (Canada)": "fr_CA.UTF-8", 
        "French (Cameroon)": "fr_CM.UTF-8",
        "French (Democratic Rep. of the Congo)": "fr_CD.UTF-8", 
        "French (France)": "fr_FR.UTF-8", 
        "French (Ivory Cast)": "fr_CI.UTF-8",
        "French (Luxembourg)": "fr_LU.UTF-8", 
        "French (Mauritania)": "fr_MR.UTF-8", 
        "French (Mauritius)": "fr_MU.UTF-8",
        "French (Senegal)": "fr_SN.UTF-8", 
        "French (Switzerland)": "fr_CH.UTF-8", 
        "French (Tunisia)": "fr_TN.UTF-8",
        
        "Galicia": "gl_ES.UTF-8", 
        "Ganda": "lg_UG.UTF-8", 
        "Georgian": "ka_GE.UTF-8",
        
        "German (Austria)": "de_AT.UTF-8", 
        "German (Germany)": "de_DE.UTF-8", 
        "German (Luxembourg)": "de_LU.UTF-8",
        "German (Switzerland)": "de_CH.UTF-8", 
        
        "Greek": "el_GR.UTF-8", 
        "Gujarati (India)": "gu_IN.UTF-8",
        "Hausa": "ha_Latn_NG.UTF-8", 
        "Hebrew": "he_IL.UTF-8", 
        "Hindi (India)": "hi_IN.UTF-8",
        "Hungarian": "hu_HU.UTF-8", 
        "Icelandic": "is_IS.UTF-8", 
        "Igbo": "ig_NG.UTF-8",
        "Indonesian": "id_ID.UTF-8", 
        
        "Italian (Italy)": "it_IT.UTF-8", 
        "Italian (Switzerland)": "it_CH.UTF-8",
        
        "Japanese": "ja_JP.UTF-8", 
        "Kannada (India)": "kn_IN.UTF-8", 
        "Kazakh": "kk_Cyrl_KZ.UTF-8",
        "Khmer": "km_KH.UTF-8", 
        "Kinyarwanda": "rw_RW.UTF-8", 
        "Konkani (India)": "kok_IN.UTF-8",
        "Korean": "ko_KR.UTF-8", 
        "Lao": "lo_LA.UTF-8", 
        "Latvian": "lv_LV.UTF-8",
        "Lithauian": "lt_LT.UTF-8", 
        "Macedonian": "mk_MK.UTF-8", 
        "Malay": "ms_MY.UTF-8",
        "Malayalam (India)": "ml_IN.UTF-8", 
        "Maltese": "mt_MT.UTF-8", 
        "Marathi (Indian)": "mr_IN.UTF-8",
        "Mongolian [Cyrillic]": "mn_Cyrl_MN.UTF-8", 
        "Nepali": "ne_NP.UTF-8", 
        "Norwegian (Bokmål)": "nb_NO.UTF-8",
        "Norwegen (Nynorsk)": "nn_NO.UTF-8", 
        "Oriya (India)": "or_IN.UTF-8", 
        "Oromo": "om_IN.UTF-8",
        "Polish": "pl_PL.UTF-8", 
        
        "Portuguese (Angola)": "pt_AO.UTF-8", 
        "Portuguese (Brazil)": "pt_BR.UTF-8",
        "Portuguese (Macao)": "pt_MO.UTF-8", 
        "Portuguese (Mozambique)": "pt_MZ.UTF-8", 
        "Portuguese (Portugal)": "pt_PT.UTF-8",
        
        "Punjabi (India)": "pa_Guru_IN.UTF-8", 
        "Romanian": "ro_RO.UTF-8", 
        "Russian": "ru_RU.UTF-8",
        
        "Serbian [Latin] (Montengro)": "sr_Latn_ME.UTF-8", 
        "Serbian [Cyrillic] (Serbia)": "sr_Cyrl_RS.UTF-8", 
        "Serbian [Latin] (Serbia)": "sr_Latn_RS.UTF-8",
        
        "Sinhala": "si_LK.UTF-8", 
        "Slovak": "sk_SK.UTF-8", 
        "Slovenian": "sl_SI.UTF-8",
        
        "Spanish (Argentina)": "es_AR.UTF-8", 
        "Spanish (Bolivia)": "es_BO.UTF-8", 
        "Spanish (Chile)": "es_CL.UTF-8",
        "Spanish (Colombia)": "es_CO.UTF-8", 
        "Spanish (Costa Rica)": "es_CR.UTF-8", 
        "Spanish (Dominican Republic)": "es_DO.UTF-8",
        "Spanish (Ecuador)": "es_EC.UTF-8", 
        "Spanish (El Salvador)": "es_SV.UTF-8", 
        "Spanish (Guatemala)": "es_GT.UTF-8",
        "Spanish (Honduras)": "es_HN.UTF-8", 
        "Spanish (Mexico)": "es_MX.UTF-8", 
        "Spanish (Nicaragua)": "es_NI.UTF-8",
        "Spanish (Panama)": "es_PA.UTF-8", 
        "Spanish (Paraguay)": "es_PY.UTF-8", 
        "Spanish (Peru)": "es_PE.UTF-8",
        "Spanish (Puerto Rico)": "es_PR.UTF-8", 
        "Spanish (Spain)": "es_ES.UTF-8", 
        "Spanish (United States)": "es_US.UTF-8",
        "Spanish (Uruguay)": "es_UY.UTF-8", 
        "Spanish (Venezuela)": "es_VE.UTF-8", 
        
        "Swahili (Kenya)": "sw_KE.UTF-8", 
        "Swahili (Tanzania)": "sw_TZ.UTF-8", 
        
        "Swedish": "sv_SE.UTF-8",
        "Tamil (India)": "ta_IN.UTF-8", 
        "Telugu (India)": "te_IN.UTF-8", 
        "Thai": "th_TH.UTF-8",
        "Turkish": "tr_TR.UTF-8", 
        "Ukrainian": "uk_UA.UTF-8", 
        "Urdu (India)": "ur_IN.UTF-8",
        "Urdu (Pakistan)": "ur_PK.UTF-8",
        "Uzbek [Cyrillic]": "uz_Cyrl_UZ.UTF-8",
        "Uzbek [Latin]": "uz_Latn_UZ.UTF-8", 
        "Viatnamese": "vi_VN.UTF-8", 
        "Welsh (United Kingdom)": "cy_GB.UTF-8",
        "Yoruba [Latin]": "yo_NG.UTF-8", 
        "Zulu": "zu_ZA.UTF-8"
}

TIMEZONE = [
    "Africa/Abidjan",
    "Africa/Accra",
    "Africa/Addis_Ababa",
    "Africa/Algiers",
    "Africa/Asmara",
    "Africa/Asmera",
    "Africa/Bamako",
    "Africa/Bangui",
    "Africa/Banjul",
    "Africa/Bissau",
    "Africa/Blantyre",
    "Africa/Brazzaville",
    "Africa/Bujumbura",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/Conakry",
    "Africa/Dakar",
    "Africa/Dar_es_Salaam",
    "Africa/Djibouti",
    "Africa/Douala",
    "Africa/El_Aaiun",
    "Africa/Freetown",
    "Africa/Gaborone",
    "Africa/Harare",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Kampala",
    "Africa/Khartoum",
    "Africa/Kigali",
    "Africa/Kinshasa",
    "Africa/Lagos",
    "Africa/Libreville",
    "Africa/Lome",
    "Africa/Luanda",
    "Africa/Lubumbashi",
    "Africa/Lusaka",
    "Africa/Malabo",
    "Africa/Maputo",
    "Africa/Maseru",
    "Africa/Mbabane",
    "Africa/Mogadishu",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Niamey",
    "Africa/Nouakchott",
    "Africa/Ouagadougou",
    "Africa/Porto-Novo",
    "Africa/Sao_Tome",
    "Africa/Timbuktu",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Anguilla",
    "America/Antigua",
    "America/Araguaina",
    "America/Argentina",
    "America/Aruba",
    "America/Asuncion",
    "America/Atikokan",
    "America/Atka",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Blanc-Sablon",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Buenos_Aires",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Catamarca",
    "America/Cayenne",
    "America/Cayman",
    "America/Chicago",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Coral_Harbour",
    "America/Cordoba",
    "America/Costa_Rica",
    "America/Creston",
    "America/Cuiaba",
    "America/Curacao",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Dominica",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Ensenada",
    "America/Fortaleza",
    "America/Fort_Nelson",
    "America/Fort_Wayne",
    "America/Glace_Bay",
    "America/Godthab",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Grenada",
    "America/Guadeloupe",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana",
    "America/Indianapolis",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Jujuy",
    "America/Juneau",
    "America/Kentucky",
    "America/Knox_IN",
    "America/Kralendijk",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Louisville",
    "America/Lower_Princes",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Marigot",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Mendoza",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/Montreal",
    "America/Montserrat",
    "America/Nassau",
    "America/New_York",
    "America/Nipigon",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota",
    "America/Nuuk",
    "America/Ojinaga",
    "America/Panama",
    "America/Pangnirtung",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Porto_Acre",
    "America/Port_of_Spain",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rainy_River",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Rosario",
    "America/Santa_Isabel",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Shiprock",
    "America/Sitka",
    "America/St_Barthelemy",
    "America/St_Johns",
    "America/St_Kitts",
    "America/St_Lucia",
    "America/St_Thomas",
    "America/St_Vincent",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Thunder_Bay",
    "America/Tijuana",
    "America/Toronto",
    "America/Tortola",
    "America/Vancouver",
    "America/Virgin",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "America/Yellowknife",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/McMurdo",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/South_Pole",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Arctic/Longyearbyen",
    "Asia/Aden",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Ashkhabad",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Bahrain",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Brunei",
    "Asia/Calcutta",
    "Asia/Chita",
    "Asia/Choibalsan",
    "Asia/Chongqing",
    "Asia/Chungking",
    "Asia/Colombo",
    "Asia/Dacca",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Harbin",
    "Asia/Hebron",
    "Asia/Ho_Chi_Minh",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Istanbul",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Kashgar",
    "Asia/Kathmandu",
    "Asia/Katmandu",
    "Asia/Khandyga",
    "Asia/Kolkata",
    "Asia/Krasnoyarsk",
    "Asia/Kuala_Lumpur",
    "Asia/Kuching",
    "Asia/Kuwait",
    "Asia/Macao",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Muscat",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Phnom_Penh",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Rangoon",
    "Asia/Riyadh",
    "Asia/Saigon",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Tel_Aviv",
    "Asia/Thimbu",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ujung_Pandang",
    "Asia/Ulaanbaatar",
    "Asia/Ulan_Bator",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vientiane",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yangon",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faeroe",
    "Atlantic/Faroe",
    "Atlantic/Jan_Mayen",
    "Atlantic/Madeira",
    "Atlantic/Reykjavik",
    "Atlantic/South_Georgia",
    "Atlantic/Stanley",
    "Atlantic/St_Helena",
    "Australia/ACT",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Canberra",
    "Australia/Currie",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/LHI",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/North",
    "Australia/NSW",
    "Australia/Perth",
    "Australia/Queensland",
    "Australia/South",
    "Australia/Sydney",
    "Australia/Tasmania",
    "Australia/Victoria",
    "Australia/West",
    "Australia/Yancowinna",
    "Brazil/Acre",
    "Brazil/DeNoronha",
    "Brazil/East",
    "Brazil/West",
    "Brazil/Brazil",
    "Canada/Atlantic",
    "Canada/Central",
    "Canada/Eastern",
    "Canada/Mountain",
    "Canada/Newfoundland",
    "Canada/Pacific",
    "Canada/Saskatchewan",
    "Canada/Yukon",
    "Chile/Continental",
    "Chile/EasterIsland",
    "Cuba",
    "Egypt",
    "Eire",
    "Etc/GMT",
    "Etc/GMT+0",
    "Etc/GMT-0",
    "Etc/GMT0",
    "Etc/GMT+1",
    "Etc/GMT-1",
    "Etc/GMT+10",
    "Etc/GMT-10",
    "Etc/GMT+11",
    "Etc/GMT-11",
    "Etc/GMT+12",
    "Etc/GMT-12",
    "Etc/GMT-13",
    "Etc/GMT-14",
    "Etc/GMT+2",
    "Etc/GMT-2",
    "Etc/GMT+3",
    "Etc/GMT-3",
    "Etc/GMT+4",
    "Etc/GMT-4",
    "Etc/GMT+5",
    "Etc/GMT-5",
    "Etc/GMT+6",
    "Etc/GMT-6",
    "Etc/GMT+7",
    "Etc/GMT-7",
    "Etc/GMT+8",
    "Etc/GMT-8",
    "Etc/GMT+9",
    "Etc/GMT-9",
    "Etc/Greenwich",
    "Etc/UCT",
    "Etc/Universal",
    "Etc/UTC",
    "Etc/Zulu",
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belfast",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Busingen",
    "Europe/Chisinau",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Guernsey",
    "Europe/Helsinki",
    "Europe/Isle_of_Man",
    "Europe/Istanbul",
    "Europe/Jersey",
    "Europe/Kaliningrad",
    "Europe/Kiev",
    "Europe/Kirov",
    "Europe/Kyiv",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/London",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Minsk",
    "Europe/Monaco",
    "Europe/Moscow",
    "Europe/Nicosia",
    "Europe/Oslo",
    "Europe/Paris",
    "Europe/Podgorica",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/San_Marino",
    "Europe/Sarajevo",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Skopje",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Tiraspol",
    "Europe/Ulyanovsk",
    "Europe/Uzhgorod",
    "Europe/Vaduz",
    "Europe/Vatican",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Europe/Zaporozhye",
    "Europe/Zurich",
    "GB",
    "GB-Eire",
    "Greenwhich",
    "Hongkong",
    "Iceland",
    "Indian/Antananarivo",
    "Indian/Chagos",
    "Indian/Christmas",
    "Indian/Cocos",
    "Indian/Comoro",
    "Indian/Kerguelen",
    "Indian/Mahe",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Indian/Mayotte",
    "Indian/Reunion",
    "Iran",
    "Israel",
    "Jamaica",
    "Japan",
    "Kwajalein",
    "Libya",
    "Mexico/BajaNorte",
    "Mexico/BajaSur",
    "Mexico/General",
    "Navajo",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Chuuk",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Enderbury",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Funafuti",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Johnston",
    "Pacific/Kanton",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Majuro",
    "Pacific/Marquesas",
    "Pacific/Midway",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Pohnpei",
    "Pacific/Ponape",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Saipan",
    "Pacific/Samoa",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
    "Pacific/Truk",
    "Pacific/Wake",
    "Pacific/Wallis",
    "Pacific/Yap",
    "Poland",
    "Portugal",
    "Singapore",
    "Turkey",
    "US/Alaska",
    "US/Aleutian",
    "US/Arizona",
    "US/Central",
    "US/Eastern",
    "US/East-Indiana",
    "US/Hawaii",
    "US/Indiana-Starke",
    "US/Michigan",
    "US/Mountain",
    "US/Pacific",
    "US/Samoa",
    "Zulu",
]

ohmyzsh = 'https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh'
figma = 'https://github.com/Figma-Linux/figma-linux/releases/download/v0.10.0/figma-linux_0.10.0_linux_x64.pacman'
miniconda = 'https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh'

ossec = "ossec-hids-local ossec-hids-sever ossec-hids-agent".split(" ")
onedrive = "onedrive-abraunegg onedrivegui-git".split(" ")
wireshark = "wireshark-cli wireshark-qt".split(" ")
clamvav = "clamav clamtk".split(" ")
texstudio = "texstudio texlive texlive-lang biber texlive-latexindent-meta texlive-plaingeneric tllocalmgr".split(" ")
geany = "geany geany-plugins".split(" ")
vscode = "visual-studio-code-bin code-marketplace".split(" ")
npm = "npm nodejs".split(" ")


OPTIONALS={
    'Chrome': 'google-chrome', 
    'JDownloader': 'jdownloader2', 
    'OpenVPN': 'openvpn',
    'Trojan': 'trojan', 
    'V2Ray': 'v2ray', 
    'Freenet': 'freenet',
    'Lokinet': 'lokinet', 
    'Thorium': 'thorium-browser-bin', 
    'Tuntox': 'tuntox',
    'WireGuard': 'wireguard-tools', 
    'httperf': 'httperf', 
    'Motrix': 'motrix',
    'Tor': 'tor', 
    'Vegeta': 'vegeta', 
    '6tunnel': '6tunnel',
    'AIDE': 'aide', 
    'GnuPG': 'gnupg', 
    'Onedrive': str(onedrive).replace('[', '').replace(']', '').replace('"', ''),
    'Metasploit': 'metasploit', 
    'OSSEC': str(ossec).replace('[', '').replace(']', '').replace('"', ''), 
    'Snort': 'snort',
    'Tiger': 'tiger', 
    'Zeek': 'zeek', 
    'Bitwarden': 'bitwarden-cli',
    'KGpg': 'kgpg', 
    'Ngrep': 'ngrep', 
    'Rootkit Hunter': 'rkhunter',
    'SSH Guard': 'sshguard', 
    'Wireshark': str(wireshark).replace('[', '').replace(']', '').replace('"', ''), 
    'ClamAV/Tk': str(clamvav).replace('[', '').replace(']', '').replace('"', ''),
    'MassHash': 'masshash', 
    'Nmap': 'nmap', 
    'Scrypt': 'scrypt',
    'StegHide': 'steghide', 
    'Xplico': 'xplico', 
    'Abiword': 'abiword',
    'gscan2pdf': 'gscan2pdf', 
    'OnlyOffice': 'onlyoffice-bin', 
    'XMind': 'xmind',
    'Cherrytree': 'cherrytree', 
    'Mark Text': 'marktext', 
    'TexStudio': str(texstudio).replace('[', '').replace(']', '').replace('"', ''),
    'Geany': str(geany).replace('[', '').replace(']', '').replace('"', ''), 
    'Micro': 'micro', 
    'TikZiT': 'tikzit',
    'BirdFont': 'birdfont', 
    'Figma': f"{figma}", 
    'Image M.': 'imagemagick',
    'nomacs': 'nomacs', 
    'Waifu2x': 'waifu2x-git', 
    'Blender': 'blender',
    'GIMP': 'gimp', 
    'imppg': 'imppg', 
    'Snappy': 'snappy-player',
    'Coulr': 'coulr', 
    'GwenView': 'gwenview', 
    'Inkscape': 'inkscape',
    'Synfig Studio': 'synfigstudio', 
    'Bazel': 'bazel', 
    'Font M.': 'font-manager',
    'Kitty': 'kitty', 
    'Miniconda': f"{miniconda}", 
    'Okular': 'okular',
    'VSCode': str(vscode).replace('[', '').replace(']', '').replace('"', ''), 
    'Cairo Dock': 'cairo-dock', 
    'GParted': 'gparted',
    'Krusader': 'krusader', 
    'Meson': 'meson', 
    'Rsync': 'rsync',
    'NPM': str(npm).replace('[', '').replace(']', '').replace('"', ''), 
    'Dolphin': 'dolphin', 
    'Gradle': 'gradle',
    'Latte Dock': 'latte-dock', 
    'Oh-My-Zsh': f"{ohmyzsh}", 
    'VMWare': 'vmware-workstation',
    "Neofetch": 'neofetch',
    "Xterm": 'xterm'
}